/**
 * 抖音登录脚本 — 打开浏览器，等待用户登录后保存 Cookie
 *
 * 使用: node login_to_douyin.js
 * 然后: 用保存的 cookie 下载视频
 */

const puppeteer = require('puppeteer-core');
const fs = require('fs');
const path = require('path');

// 查找 Chrome 可执行文件
function findChrome() {
    const paths = [
        'C:/Program Files/Google/Chrome/Application/chrome.exe',
        'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe',
        process.env.LOCALAPPDATA + '/Google/Chrome/Application/chrome.exe',
        process.env.PROGRAMFILES + '/Google/Chrome/Application/chrome.exe',
        process.env['PROGRAMFILES(X86)'] + '/Google/Chrome/Application/chrome.exe',
    ];
    for (const p of paths) {
        if (fs.existsSync(p)) return p;
    }
    return null;
}

const chromePath = findChrome();
const cookieSavePath = path.join(__dirname, 'cookies_puppeteer.txt');

async function main() {
    console.log('正在启动浏览器...');

    const browser = await puppeteer.launch({
        executablePath: chromePath,
        headless: false,
        defaultViewport: { width: 1280, height: 800 },
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage',
        ],
    });

    const page = await browser.newPage();
    await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36');

    // 导航到抖音 — 用 domcontentloaded 更快，不用等所有资源加载完
    await page.goto('https://www.douyin.com/', { waitUntil: 'domcontentloaded', timeout: 60000 });

    console.log('========================================');
    console.log('  ✅ 浏览器窗口已打开！');
    console.log('  请在弹出的浏览器中登录你的抖音账号');
    console.log('  (扫码 / 手机号 / 抖音号登录都可以)');
    console.log('  登录成功后，回到这里按 Enter 键继续...');
    console.log('========================================');

    // 等待用户按 Enter
    await new Promise(resolve => {
        process.stdin.once('data', resolve);
    });

    // 获取 Cookie
    const cookies = await page.cookies();

    // 保存为 Netscape 格式 (yt-dlp 兼容)
    let netscapeContent = '# Netscape HTTP Cookie File\n';
    netscapeContent += '# Generated by login_to_douyin.js\n\n';

    for (const c of cookies) {
        const domain = c.domain.startsWith('.') ? c.domain : '.' + c.domain;
        const includeSub = 'TRUE';
        const path2 = c.path || '/';
        const secure = c.secure ? 'TRUE' : 'FALSE';
        const expires = Math.floor((c.expires || (Date.now() / 1000 + 86400 * 30)));
        const name = c.name;
        const value = c.value;
        netscapeContent += `${domain}\t${includeSub}\t${path2}\t${secure}\t${expires}\t${name}\t${value}\n`;
    }

    fs.writeFileSync(cookieSavePath, netscapeContent, 'utf-8');
    console.log(`\n✅ Cookie 已保存: ${cookieSavePath}`);
    console.log(`   共 ${cookies.length} 个 Cookie`);

    // 同时保存为 dydl 兼容格式
    const dydlDir = path.join(process.env.APPDATA || path.join(require('os').homedir(), 'AppData/Roaming'), 'dydl');
    fs.mkdirSync(dydlDir, { recursive: true });
    fs.writeFileSync(path.join(dydlDir, 'cookie.txt'), netscapeContent, 'utf-8');
    console.log(`✅ 已同步到 dydl: ${path.join(dydlDir, 'cookie.txt')}`);

    await browser.close();
    console.log('\n现在可以运行批量下载了！');
}

main().catch(err => {
    console.error('错误:', err.message);
    process.exit(1);
});
